### PR TITLE
Print a PCI device map on startup

### PR DESCRIPTION
**Pull request by allanlw**
Also some minor other boot message changes.

I didn't take the time to look at the information that ide.c was printing out but it looks useless and messes up the PCI device map.

### CODE REVIEW

**Comment by allanlw** [comment]
After the last two commits, the bootup now looks like:
```
Welcome to GeorgeOS, Multiboot Edition!
PCI 00:00.00 (class: 0600 vendor: 8086) Unknown
PCI 00:01.00 (class: 0601 vendor: 8086) Unknown
PCI 00:01.01 (class: 0101 vendor: 8086) IDE Controller
PCI 00:01.03 (class: 0680 vendor: 8086) Unknown
PCI 00:02.00 (class: 0300 vendor: 1234) Unknown
PCI 00:03.00 (class: 0200 vendor: 8086) Unknown
ACPI RSDT Init
ACPI FACP Init
ACPI DSDT Init
ACPI SSDT Init
ACPI APIC Init
ACPI HPET Init
Launching userspace.
```

**Comment by gsilvis** [comment]
Output looks very nice.  Can you squash the minor tweak commits together?

**Comment by allanlw** [comment]
Output is now:
```
Welcome to GeorgeOS, Multiboot Edition!
PCI 00:00.00 (class: 0600 vendor: 8086) Host Bridge (Unhandled)
PCI 00:01.00 (class: 0601 vendor: 8086) ISA Bridge (Unhandled)
PCI 00:01.01 (class: 0101 vendor: 8086) IDE Controller
PCI 00:01.03 (class: 0680 vendor: 8086) Other Bridge (Unhandled)
PCI 00:02.00 (class: 0300 vendor: 1234) VGA Controller (Unhandled)
PCI 00:03.00 (class: 0200 vendor: 8086) Ethernet Controller (Unhandled)
ACPI RSDT Init
ACPI FACP Init
ACPI DSDT Init
ACPI SSDT Init
ACPI APIC Init
ACPI HPET Init
Launching userspace.
```

**Comment by gsilvis** [comment]
LGTM, Approval

**Pull request merged**
